"""Kamus normalisasi kata gaul/singkatan Bahasa Indonesia informal -> baku.

Dipakai pada tahap Expand Contractions. Daftar ini tidak lengkap, cukup untuk
menormalkan singkatan/kata gaul yang paling umum muncul di komentar media sosial.
"""

SLANG_DICT = {
    "yg": "yang", "yang": "yang",
    "dgn": "dengan", "dg": "dengan",
    "tdk": "tidak", "tak": "tidak", "ga": "tidak", "gak": "tidak",
    "gk": "tidak", "nggak": "tidak", "ngga": "tidak", "kaga": "tidak",
    "udah": "sudah", "udh": "sudah", "dah": "sudah", "sdh": "sudah",
    "blm": "belum", "belom": "belum",
    "sm": "sama", "ama": "sama",
    "utk": "untuk", "buat": "untuk",
    "dr": "dari",
    "krn": "karena", "karna": "karena", "krna": "karena",
    "jgn": "jangan",
    "bgt": "banget",
    "gpp": "tidak apa apa", "gapapa": "tidak apa apa", "gaapa": "tidak apa apa",
    "gimana": "bagaimana", "gmn": "bagaimana", "gmna": "bagaimana",
    "knp": "kenapa", "kenapa": "kenapa",
    "emg": "memang", "emang": "memang",
    "tp": "tapi", "tapi": "tapi",
    "org": "orang",
    "aja": "saja", "aj": "saja",
    "km": "kamu", "kmu": "kamu",
    "gw": "saya", "gue": "saya", "gua": "saya", "ane": "saya",
    "lu": "kamu", "loe": "kamu", "lo": "kamu",
    "gtu": "begitu", "gitu": "begitu",
    "bs": "bisa", "bsa": "bisa",
    "jd": "jadi",
    "dlm": "dalam",
    "sbg": "sebagai",
    "spy": "supaya",
    "hrs": "harus",
    "cm": "cuma", "cma": "cuma",
    "skrg": "sekarang", "skg": "sekarang",
    "td": "tadi",
    "sy": "saya",
    "dpt": "dapat",
    "trs": "terus", "trus": "terus",
    "klo": "kalau", "kalo": "kalau",
    "bikin": "membuat",
    "liat": "lihat",
    "pake": "pakai",
    "banget": "banget",
    "dlu": "dulu",
    "skalian": "sekalian",
    "moga": "semoga",
    "makasih": "terima kasih", "mksh": "terima kasih", "thx": "terima kasih",
    "min": "admin",
    "org2": "orang orang",
    "pdhl": "padahal", "padahal": "padahal",
    "sptnya": "sepertinya", "kyk": "seperti", "kaya": "seperti", "kayak": "seperti",
    "gaes": "teman teman", "gais": "teman teman", "guys": "teman teman",
    "wkwk": "haha", "wkwkwk": "haha", "wkwkwkwk": "haha", "haha": "haha",
    "anjir": "aduh", "anjay": "aduh",
    "min2": "admin admin",
    "tuh": "itu",
    "nih": "ini",
    "kek": "seperti",
    "mager": "malas gerak",
    "japri": "jalur pribadi",
    "ampe": "sampai", "smpe": "sampai", "sampe": "sampai",
    "brgkt": "berangkat",
    "bnyk": "banyak", "byk": "banyak",
    "sdgkan": "sedangkan",
    "gada": "tidak ada", "ga ada": "tidak ada",
    "presiden": "presiden",
}
